# Generated by Django 5.1.3 on 2025-01-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerimage',
            name='updated_at',
        ),
    ]
