# Generated by Django 5.1.3 on 2025-01-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('header', 'Header'), ('gallery', 'Gallery')], max_length=7)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='headerimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
        migrations.AddField(
            model_name='headerimage',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(),
        ),
    ]
